- src: https://visitor:visitor@pdihub.hi.inet/smartdigitsre/ansible-role-smd-bootstrap.git
  scm: git
  version: testing
  name: ansible-role-smd-bootstrap
- src: https://visitor:visitor@pdihub.hi.inet/smartdigitsre/ansible-role-smd-docker.git
  scm: git
  version: community-edition
  name: ansible-role-smd-docker
- src: https://visitor:visitor@pdihub.hi.inet/smartdigitsre/ansible-role-smd-repos.git
  scm: git
  version: master
  name: ansible-role-smd-repos
- src: https://visitor:visitor@pdihub.hi.inet/smartdigitsre/ansible-role-smd-chrony.git
  scm: git
  version: master
  name: ansible-role-smd-chrony
- src: https://visitor:visitor@pdihub.hi.inet/smartdigitsre/ansible-role-smd-rhn.git
  scm: git
  version: master
  name: ansible-role-smd-rhn
